Sorry for the doubly quadruple PR - i'm new to publishing on OPAM
Baguette# is an exotic programming language based on french pastries
Baguette_base contains the Lexer/Parser
Baguette_functions contains the Conditions/Math/Array/String modules and manipulation of the language (the Baguette# Standard Library) 
and the function modules who's job is to match function from their pastry name to real name
Baguette_sharp is the interpreter while
Baguette-sharp is the executable file for the REPL
